### PR TITLE
multiple bucket deployment with integration tests

### PR DESCRIPTION
**Pull request by rstittda**
Committer: Russell Stitt <rstitt@da.com.au>

On branch feature/finch-56
Changes to be committed:
	modified:   .gitignore
	modified:   index.js
	new file:   test/alternate/default.html
	modified:   test/automated_tests.py
	new file:   test/config_files/obj-headers-custom-index-m.yml
	new file:   test/config_files/obj-headers-standard-index-m.yml
	new file:   test/config_files/standard-deploy-m1.yml
	new file:   test/config_files/standard-deploy-m2.yml
	new file:   test/config_files/standard-deploy-m3.yml
	modified:   test/config_files/standard-deploy-use1.yml

### Background

[reference to original issue or other discussion]

### Proposed changes

The serverless.yml can stay the same with 
```yaml
custom:
  client:
    bucketName: BUCKETNAME
      indexDocument: index.html
      errorDocument: error.html
```
but also now support the client as an array:

```yaml
custom:
  client:
    - bucketName: BUCKET1
      indexDocument: index.html
      errorDocument: error.html
    - bucketName: BUCKET2
      distributionFolder: alternate
      indexDocument: default.html
      errorDocument: error.html
```
The javascript client object accepts either.

I haven't updated the documentation but am happy to get the request accepted.
 
[list of features added and/or changed]

### Proposed reviewers (optional)

[@ mentions of other contributors]

### CODE REVIEW

**Comment by fernando-mc** [comment]
@rstittda From first glance this looks great. I've got to do some manual work to run all the tests and confirm how your new ones work but I like that they're enforcing teardown which should make them easier to run for future contributors.

Just getting caught up now and I have a conference coming up but I'll try to get to this sometime in the next week or two. 

@linusmarco if you have time to review/merge before then feel free.

**Comment by rstittda** [comment]
@fernando-mc/serverless-finch<mailto:reply@reply.github.com> Okay. If there is a better pattern for python tests I am happy to look into it. As you already noted, I couldn’t create your buckets from my service account. I chose southeast since that is where I am located.

**Comment by junjettrasmonte** [comment]
I was able to deploy to multiple buckets without any changes to this package.
`client:
    bucketName: ${opt:client}-${opt:stage, 'dev'}.domain.tld
    distributionFolder: client/${opt:client}/dist
    indexDocument: index.html
    errorDocument: index.html`

my file structure is 
./serverless.yml
./client/client1/dist/
./client/client2/dist/
./client/client3/dist/

then to deploy 

`sls client deploy --stage dev --client client1`
`sls client deploy --stage dev --client client2`
`sls client deploy --stage dev --client client3`

**Comment by rstittda** [comment]
Hi, it has been a while but I have run my PR tests again and added some documentation. I'm still happy with the PR.

**Comment by Shereef** [comment]
This branch is so old now and as @junjettrasmonte [mentioned](https://github.com/fernando-mc/serverless-finch/pull/93#issuecomment-682383923) above that it's possible without further changes

I will close this PR but if you feel this is a mistake please resubmit this PR when you rebase off of master and testing it with serverless 3

Please do test what @junjettrasmonte [suggested](https://github.com/fernando-mc/serverless-finch/pull/93#issuecomment-682383923) and let us know.

**Pull request closed without merging**
