### PR TITLE
add support for custom bucket policy configs

### PR DESCRIPTION
**Pull request by jsphweid**
### Background

Reimplement this: #15 

### Proposed changes

The ability to add a custom bucket config.

### CODE REVIEW

**Comment by jsphweid** [comment]
Also, I realize that there are a few code styling changes. I didn't intend this, but the hook must have changed them. I believe they fall within the style guidelines outlined by prettier (100 max line length and single quotes) but I'm not sure why these things were not corrected on an earlier commit.

**Comment by fernando-mc** [comment]
@jsphweid Thanks for the PR! And no worries. I'm happy to include syntax fixes in the PR. Overall looks like a good change.

Have you had a chance to test this?

**Comment by jsphweid** [comment]
@fernando-mc I tested this and it works for me. If it has any trouble reading / parsing the file, the try-catch will just make it resort to the default.

On second thought, I'm not sure what will happen when someone uses a valid json file but one that aws doesn't recognize as a valid policy. I'll have to try this tomorrow at work. I wonder what whould be a good thing to do in that case...?

**Comment by jsphweid** [comment]
@fernando-mc so if something is invalid, it appears that it will just halt right there. But in this case, all my items are gone because the delete happens before the policy attachment. Maybe it'd be better if it tries to attach the policy first just in case that fails?

How would you like to see it?

```
? Do you want to proceed? true
Serverless: Looking for bucket...
Serverless: Bucket found...
Serverless: Deleting all objects from bucket...
Serverless: Configuring bucket...
Serverless: Configuring policy for bucket...

  Serverless Error ---------------------------------------

  ServerlessError: The policy must contain a valid version string
```

**Comment by linusmarco** [comment]
@jsphweid you should be able to use the `iam.simulateCustomPolicy` method in the AWS SDK to validate the policy:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/IAM.html#simulateCustomPolicy-property

Also, please make sure that you add this and any other relevant validation checks on the new `bucketPolicyFile` configuration option to `lib/validate.js`. That is where we keep all the validation checks to make sure that all of the validation runs prior to any bucket removal and/or deployment.

And thanks for adding this functionality!

**Comment by jsphweid** [comment]
I'll look into this tonight

**Comment by jsphweid** [comment]
@fernando-mc I moved the basic json parsing try/catch validation to validate.js where it makes more sense. @linusmarco It looks like that introduces an async operation to the currently synchronous validation process. I could make it look the cleanest with async/await. Can I use that in this project? What minimum node version do you want to support because that's 7.6 I believe.

**Comment by fernando-mc** [comment]
@linusmarco @jsphweid This seems to pass my tests. Merging.

**Pull request merged**
