### PR TITLE
Added the ability to preserve files during deployment

### PR DESCRIPTION
**Pull request by ernestwallace**

### CODE REVIEW

**Comment by fernando-mc** [comment]
@ernestwallace This makes sense as a feature. I think it could save time and reduce cost by avoiding deleting things. Here are a few questions before I proceed here:

1. Will this block the `sls client remove` functionality? From a glance over this it looks like it could. Have you tested your change against that? I think if you have the `keepFiles: true` set it would block `sls client remove`. Could be wrong there - I still have to test it.

2. Can you update the config portion of the readme with how this works. Include it in the config the same way as the other values. The updated Warning line is good, but we also need a config example update.

**Comment by ernestwallace** [comment]
Good call on the remove.  I'll get that corrected and update the PR.

**Comment by fernando-mc** [comment]
Awesome, thanks @ernestwallace! Assigning this to you until then.

**Comment by evanseeds** [comment]
@ernestwallace it looks like this same functionality is implemented in #28, with a few more options as well

**Comment by ernestwallace** [comment]
@evanseeds @fernando-mc Awesome - I'll close out this PR.  Thanks for the heads up!

**Pull request closed without merging**
