### PR TITLE
Code coverage reporting

### PR DESCRIPTION
**Pull request by mikejpeters**
Generates code coverage reports for unit tests, and pushes them to [codecov.io](https://about.codecov.io/).

Notes
- codecov.io is free for open source
- I think @fernando-mc may need to enable integration for this repo at https://about.codecov.io/sign-up/

### CODE REVIEW

**Review by Shereef — APPROVED** [review]

**Comment by fernando-mc** [comment]
@mikejpeters I think have have an account and I see it in the dashboard. Do you need me to set new secrets with the token or something?

**Comment by mikejpeters** [comment]
@fernando-mc I wasn't sure but it seems like it already works fine. I imagine the purpose of having an account there is that you can manage a few settings on that end? Like maybe whether it will fail the check if coverage is below a certain %? I haven't actually ever integrated a repo I own with codecov.io so I'm mostly guessing.

But anyway I think this is ready to merge if you think it's good

**Comment by Shereef** [comment]
If it's anything like sonar cloud you the integration is at the account level
then you are allowed to share all repos with it or certain repos
if @fernando-mc already shared all repos it would work

**Comment by Shereef** [comment]
https://github.com/fernando-mc/serverless-finch/actions/runs/1912672456 Integration tests passed for this branch FYI

**Comment by Shereef** [comment]
@mikejpeters are we waiting for something or should I rebase and merge this?

**Comment by fernando-mc** [comment]
No blocks from me. Looks like it's outputting the report now so let me know if you need anything else otherwise go for it on the merge.

**Pull request merged**
