### PR TITLE
Pre and Post Deploy hooks

### PR DESCRIPTION
**Pull request by itsjesseyo**
### Background

#97 pre  and  post build commands

### Proposed changes

add before and after hooks to the deploy process and call commands passed in to the yml. I used exec for simplicity, but it has a disadvantage that the buffers can fill up.

### Proposed reviewers (optional)

[@ mentions of other contributors]

### CODE REVIEW

**Comment by fernando-mc** [comment]
Thanks for the PR @itsjesseyo! I appreciate the contribution, have you taken a look at this by any chance? https://github.com/mvila/serverless-plugin-scripts

I'm wondering if it would accomplish much of the same sort of thing?

**Comment by itsjesseyo** [comment]
It does, but there are certainly usage implications. Users would have to make two other custom blocks, and make two additional command-line commands to trigger it. Addtionally, it's another dependency for what is a very common task - npm run build. If it's not a standard feature in this plugin, then I personally would just run npm run build myself. it  would amount to less work than using serverless-plugins-scripts.

**Comment by fernando-mc** [comment]
@itsjesseyo Really appreciate the work here. 

If we're thinking about a build process would this add something over adding your build commands to an `npm run build` or `npm run deploy`?

I would see `npm run deploy` == `npm run build && serverless client deploy`. 

I'm hesitant to add another way to do it without understanding the use case better. If there's a use case I don't know of that isn't covered by easily adding commands in `npm run ___` or by using the plugin I mentioned I'm for it. I could see how it might be cumbersome to use a separate plugin when you just want to trigger a build whenever you're deploying with serverless finch.

Let me know what you think, if we do go forward with this PR here's a few things to add:

1. Add readme details for the usage, examples etc.
2. Remove extra newlines in the second file

**Comment by itsjesseyo** [comment]
That's fair, and it is the kind of thing that opens up room to get bug reports coming in for an end users bad usage.

**Comment by fernando-mc** [comment]
I really appreciate the detailed examples here. I think there's plenty of valid use cases in there but I'm still trying to understand why they are not already easily achieved with the current solutions.

Take the buildpolicy example - I think that was in reference to bucket policies? But correct me here please. We currently have options to deploy stage based `bucketPolicyFile`s? You can have custom policies for each stage in a version controlled JSON file. 

Posting slack messages for deploy processes also makes sense to me. I could see why that is useful, but that would seem to fit better in a CI/CD system like Framework Pro/Circle CI etc. - I think [Framework Pro](http://dashboard.serverless.com/) has these events [already](https://serverless.com/framework/docs/dashboard/cicd/notifications/)?

VPN IP - So this is a single external file that you'd like to reference and pull the contents into your bucket policy somehow? This seems potentially like a build system step? It's an interesting use case here, but I'd expect you want to keep the actual policies in version control so I'd still refer to the version controlled JSON file that you update and then run another `serverless client deploy`.

My main concern here is that adding *another* way to do something means supporting another way to do something. I'm selfish and lazy so I'd rather have less options to manage and maintain myself unless they provide a significant new functionality that can't already be achieved elsewhere. (Like #96 which I'm still working on, thanks for the PR there again!)

**Comment by fernando-mc** [comment]
Going to close this for now, but feel free to reopen if you have other discussion or disagree with the decision.

**Pull request closed without merging**
