### PR TITLE
List of files as --file argument 

### PR DESCRIPTION
**Pull request by Akababa**
It works but is probably missing all the edge cases due to my mindless copy-pasting. It would be nice to integrate git diff somehow but probably not worth the headache.

### CODE REVIEW

**Comment by fernando-mc** [comment]
@Akababa I pushed a new version with some new functionality tonight - I'll be looking at how I can resolve the conflicts given those changes but I'd like to get this in too.

**Comment by Akababa** [comment]
Awesome! I've been using this on my own for a while now but it feels nice to have my first open source contribution.

**Comment by fernando-mc** [comment]
@Akababa I'm putting this back on my agenda for the next release. Sorry about the delay here.

**Comment by fernando-mc** [comment]
After a bit more review I think this may be impacted by the changes to https://github.com/fernando-mc/serverless-finch/pull/18

Can you pull the latest version and toss these changes in again? I'd like to include this.

**Comment by amsross** [comment]
Is it possible to take a second look at the existing `_uploadDirectory` and `_uploadFiles` methods and where they are called in order to use more of the existing code path? It looks to me that this functionality could be achievable further down the call chain with a good bit less (duplicate) logic.

**Comment by fernando-mc** [comment]
Leaving this open for now, but it will need to be updated to reflect recent changes and conform to style checks.

**Comment by linusmarco** [comment]
@Akababa, if you have any questions or need any help merging the recent linting/docs changes into this PR, just let me know.

**Comment by fernando-mc** [comment]
Closing for now. We can revisit in the future if conflicts are resolved.

**Pull request closed without merging**
