### PR TITLE
Give more instructions on bucket policy.

### PR DESCRIPTION
**Pull request by jrschumacher**
### Background

Since `[some/path/here.json]` translates to `["some/path/here.json"]` it is confusing and I thought the policy required an array of strings.

### Proposed changes

Update the README and us `"some/path/policy.json"` instead. Also added some tips about env paths since finch will try and look in serverless-finch module directory path for relative path policies.

### CODE REVIEW

**Comment by jrschumacher** [comment]
@fernando-mc

**Comment by fernando-mc** [comment]
@jrschumacher thanks for the PR!

Can we keep the default as "/path/to/policy.json" but also make sure to add the additional example with ${env:PWD} in the notes? 

Something like this maybe?
```
 _Note: You can also use `${env:PWD}` if you want to dynamically specify the policy within your repo. for example: 

bucketPolicyFile: "${env:PWD}/path/to/policy.json"

 Additionally, you will want to specify different policies depending on your stage using `${self:provider.stage}` to ensure your `BUCKET_NAME` corosponds to the stage._

This could also use an example.
```

Thanks for the suggestions!

**Comment by jrschumacher** [comment]
Sure I'll make the change. Would you also accept a PR if I updated the README to avoid the use of brackets throughout (unless the option is an array)?

**Comment by fernando-mc** [comment]
@jrschumacher I think that would be fine and makes sense.

Please keep them in cases like this:
`serverless client deploy [--region $REGION] [--no-delete-contents]`

Otherwise I think you're correct and that they imply an array.

Nice catch!

**Comment by jrschumacher** [comment]
@fernando-mc thoughts?

**Pull request merged**
